FEATURES = [
    {
        "name": "age",
        "label": "Age",
        "group": "Demographics",
        "default": 68,
        "normal": "Dementia risk increases with age, especially after 65.",
        "direction": "higher",
    },
    {
        "name": "education_years",
        "label": "Years of Education",
        "group": "Demographics",
        "default": 12,
        "normal": "More years of formal education may provide cognitive reserve.",
        "direction": "lower",
    },
    {
        "name": "family_history",
        "label": "Family History",
        "group": "History",
        "default": 0,
        "normal": "A family history of dementia can increase risk.",
        "direction": "higher",
    },
    {
        "name": "apoe4",
        "label": "APOE-e4 Carrier",
        "group": "Biomarkers",
        "default": 0,
        "normal": "APOE-e4 is associated with higher Alzheimer-type dementia risk.",
        "direction": "higher",
    },
    {
        "name": "mmse",
        "label": "MMSE Score",
        "group": "Clinical Scores",
        "default": 27,
        "normal": "MMSE usually ranges from 0 to 30; lower scores suggest impairment.",
        "direction": "lower",
    },
    {
        "name": "moca",
        "label": "MoCA Score",
        "group": "Clinical Scores",
        "default": 25,
        "normal": "MoCA usually ranges from 0 to 30; lower scores may detect early impairment.",
        "direction": "lower",
    },
    {
        "name": "cdr",
        "label": "Clinical Dementia Rating",
        "group": "Clinical Scores",
        "default": 0,
        "normal": "CDR values above 0 indicate increasing cognitive and functional concern.",
        "direction": "higher",
    },
    {
        "name": "memory_recall",
        "label": "Memory Recall Score",
        "group": "Behavioral",
        "default": 8,
        "normal": "Lower delayed recall is a common early marker of cognitive decline.",
        "direction": "lower",
    },
    {
        "name": "orientation",
        "label": "Orientation Score",
        "group": "Behavioral",
        "default": 9,
        "normal": "Orientation difficulties can indicate cognitive impairment.",
        "direction": "lower",
    },
    {
        "name": "daily_function",
        "label": "Daily Function Score",
        "group": "Behavioral",
        "default": 8,
        "normal": "Lower function suggests difficulty with daily tasks.",
        "direction": "lower",
    },
    {
        "name": "mood_change",
        "label": "Mood Change Severity",
        "group": "Behavioral",
        "default": 2,
        "normal": "Mood or personality changes may accompany early dementia.",
        "direction": "higher",
    },
    {
        "name": "sleep_quality",
        "label": "Sleep Quality",
        "group": "Behavioral",
        "default": 7,
        "normal": "Lower sleep quality can worsen cognition and daily functioning.",
        "direction": "lower",
    },
    {
        "name": "wandering",
        "label": "Wandering / Getting Lost",
        "group": "Behavioral",
        "default": 0,
        "normal": "Getting lost in familiar places is a strong functional warning sign.",
        "direction": "higher",
    },
    {
        "name": "medication_adherence",
        "label": "Medication Adherence",
        "group": "Behavioral",
        "default": 8,
        "normal": "Difficulty managing medication may reflect executive dysfunction.",
        "direction": "lower",
    },
    {
        "name": "hypertension",
        "label": "Hypertension",
        "group": "History",
        "default": 0,
        "normal": "Vascular risk factors can contribute to cognitive decline.",
        "direction": "higher",
    },
    {
        "name": "diabetes",
        "label": "Diabetes",
        "group": "History",
        "default": 0,
        "normal": "Diabetes is associated with vascular and cognitive risk.",
        "direction": "higher",
    },
    {
        "name": "amyloid_beta",
        "label": "CSF Amyloid-beta",
        "group": "Biomarkers",
        "default": 900,
        "normal": "Lower CSF amyloid-beta can be associated with amyloid deposition.",
        "direction": "lower",
    },
    {
        "name": "tau",
        "label": "CSF Tau",
        "group": "Biomarkers",
        "default": 300,
        "normal": "Higher tau can indicate neuronal injury.",
        "direction": "higher",
    },
]

FEATURE_NAMES = [feature["name"] for feature in FEATURES]
FEATURE_LABELS = {feature["name"]: feature["label"] for feature in FEATURES}
DEFAULTS = {feature["name"]: feature["default"] for feature in FEATURES}
DIRECTIONS = {feature["name"]: feature["direction"] for feature in FEATURES}

CLASS_LABELS = ["Low Risk", "Moderate Risk", "High Risk"]
